algoritmo "bare*expoente"
// Função :
// Autor : igor de jesus silva
// Data : //
// Seção de Declarações 
Var

number,number1,result,cont:inteiro
Inicio

escreval("Digite a base")
leia(number)
escreval("Digite o expoente")
leia(number1)

result<-1
para cont de 1 ate number1 faca
   result<-result*number

fimpara
escreval("O resultado de ",number," elevado a ",number1," é ",result)
Fimalgoritmo
