algoritmo "tabuada"
// Função : tabuada
// Autor :  igor de jesus silva
// Data : //
// Seção de Declarações 
var
number:real
number2:inteiro
inicio
// Seção de Comandos
escreval("ola esse algoritimo faz a tabuada do numero digitado")
escreval("digite o numero")
leia(number)
number2 <- 0

para number2 de 1 ate 10 faca
escreval(number2,"*",number, " = ", number2*number)
fimpara
fimalgoritmo
