algoritmo "alturaTime"
// Função :
// Autor :  igor de jesus silva
// Data : //
// Seção de Declarações 
Var

number, number1: inteiro
heigth, soma, average: real
Inicio

soma<-0
escreva("quantos jogadores tem no time?")
leia(number)

 Para number1 de 1 ate number faca
    escreval("Digite a altura do ",number1)
    leia(heigth)
    soma<-soma+heigth
 Fimpara

 average<-soma/number
 escreval("média=",average)
Fimalgoritmo
